import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import customersRouter from "./customers";
import customerDetailsRouter from "./customer-details";
import productsRouter from "./products";
import productAttributesRouter from "./product-attributes";
import productVariantsRouter from "./product-variants";
import suppliersRouter from "./suppliers";
import ordersRouter from "./orders";
import processStockRouter from "./process-stock";
import purchasingRouter from "./purchasing";
import worksheetsRouter from "./worksheets";
import settingsRouter from "./settings";
import dispatchRouter from "./dispatch";
import xeroRouter from "./xero";
import tasksRouter from "./tasks";
import productCategoriesRouter from "./product-categories";
import portalRouter from "./portal";
import demoRouter from "./demo";
import invoicesRouter from "./invoices";
import stockRouter from "./stock";
import stripePaymentsRouter from "./stripe-payments";
import reportsRouter from "./reports";
import staffAuthRouter from "./staff-auth";
import messagesRouter from "./messages";
import selectExtraRouter from "./select-extra";
import quotesRouter from "./quotes";
import enquiriesRouter from "./enquiries";
import wcEnquiriesRouter from "./wc-enquiries";
import wooRouter from "./woo";
import staffMembersRouter from "./staff-members";
import bundlesRouter from "./bundles";
import feedbackRouter from "./feedback";
import socialPostsRouter from "./social-posts";
import chatRouter from "./chat";
import tvRouter from "./tv";
import reEngagementRouter from "./re-engagement";
import messageTemplatesRouter from "./message-templates";
import shopRouter from "./shop";
import shopAuthRouter from "./shop-auth";
import reviewsRouter from "./reviews";
import categoryManagementRouter from "./category-management";
import workflowsRouter from "./workflows";
import imageMigrationRouter from "./image-migration";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(portalRouter);
router.use(demoRouter);
router.use(customersRouter);
router.use(customerDetailsRouter);
router.use(productsRouter);
router.use(productAttributesRouter);
router.use(productVariantsRouter);
router.use(suppliersRouter);
router.use(ordersRouter);
router.use(processStockRouter);
router.use(purchasingRouter);
router.use(worksheetsRouter);
router.use(settingsRouter);
router.use(dispatchRouter);
router.use(xeroRouter);
router.use(tasksRouter);
router.use(productCategoriesRouter);
router.use(invoicesRouter);
router.use(stockRouter);
router.use(stripePaymentsRouter);
router.use(reportsRouter);
router.use(staffAuthRouter);
router.use(messagesRouter);
router.use(selectExtraRouter);
router.use(quotesRouter);
router.use(enquiriesRouter);
router.use(wcEnquiriesRouter);
router.use(wooRouter);
router.use(staffMembersRouter);
router.use(bundlesRouter);
router.use(feedbackRouter);
router.use(socialPostsRouter);
router.use(chatRouter);
router.use(tvRouter);
router.use(reEngagementRouter);
router.use(messageTemplatesRouter);
router.use(shopRouter);
router.use(shopAuthRouter);
router.use(reviewsRouter);
router.use(categoryManagementRouter);
router.use(workflowsRouter);
router.use(imageMigrationRouter);

export default router;
