// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/po-dialog/NoEmail.tsx": () => import("../components/mockups/po-dialog/NoEmail.tsx"),
  "./components/mockups/po-dialog/WithEmail.tsx": () => import("../components/mockups/po-dialog/WithEmail.tsx"),
  "./components/mockups/cat-tiles/BrandWash.tsx": () => import("../components/mockups/cat-tiles/BrandWash.tsx"),
  "./components/mockups/cat-tiles/DiagonalFlash.tsx": () => import("../components/mockups/cat-tiles/DiagonalFlash.tsx"),
  "./components/mockups/cat-tiles/RevealPanel.tsx": () => import("../components/mockups/cat-tiles/RevealPanel.tsx")
};
